# This file is auto-generated by core/scripts/generate-python-exchanges.js
# Do not edit manually.
# To regenerate: npm run generate:sdk:all --workspace=pmxt-core
# Source of truth: core/src/server/exchange-factory.ts (createExchange function)

from typing import Any, Dict, Optional

from .client import Exchange

class Polymarket(Exchange):
    """Polymarket exchange client."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        api_secret: Optional[str] = None,
        passphrase: Optional[str] = None,
        private_key: Optional[str] = None,
        proxy_address: Optional[str] = None,
        signature_type: Optional[Any] = "gnosis-safe",
        base_url: Optional[str] = None,
        auto_start_server: Optional[bool] = None,
        pmxt_api_key: Optional[str] = None,
    ):
        """
        Initialize Polymarket client.

        Args:
            api_key: API key for authentication (optional)
            api_secret: API secret for authentication (optional)
            passphrase: Passphrase for authentication (optional)
            private_key: Private key for authentication (optional)
            proxy_address: Proxy/smart wallet address (optional)
            signature_type: Signature type (optional)
            base_url: Base URL of the PMXT sidecar server
            auto_start_server: Automatically start server if not running (default: True)
            pmxt_api_key: Hosted PMXT API key (optional; enables hosted mode)
        """
        super().__init__(
            exchange_name="polymarket",
            api_key=api_key,
            private_key=private_key,
            proxy_address=proxy_address,
            signature_type=signature_type,
            base_url=base_url,
            auto_start_server=auto_start_server,
            pmxt_api_key=pmxt_api_key,
        )

        self.api_secret = api_secret
        self.passphrase = passphrase

    def _get_credentials_dict(self) -> Optional[Dict[str, Any]]:
        creds = super()._get_credentials_dict() or {}
        if self.api_secret:
            creds["apiSecret"] = self.api_secret
        if self.passphrase:
            creds["passphrase"] = self.passphrase
        return creds if creds else None


class Limitless(Exchange):
    """Limitless exchange client."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        api_secret: Optional[str] = None,
        passphrase: Optional[str] = None,
        private_key: Optional[str] = None,
        base_url: Optional[str] = None,
        auto_start_server: Optional[bool] = None,
        pmxt_api_key: Optional[str] = None,
    ):
        """
        Initialize Limitless client.

        Args:
            api_key: API key for authentication (optional)
            api_secret: API secret for authentication (optional)
            passphrase: Passphrase for authentication (optional)
            private_key: Private key for authentication (optional)
            base_url: Base URL of the PMXT sidecar server
            auto_start_server: Automatically start server if not running (default: True)
            pmxt_api_key: Hosted PMXT API key (optional; enables hosted mode)
        """
        super().__init__(
            exchange_name="limitless",
            api_key=api_key,
            private_key=private_key,
            base_url=base_url,
            auto_start_server=auto_start_server,
            pmxt_api_key=pmxt_api_key,
        )

        self.api_secret = api_secret
        self.passphrase = passphrase

    def _get_credentials_dict(self) -> Optional[Dict[str, Any]]:
        creds = super()._get_credentials_dict() or {}
        if self.api_secret:
            creds["apiSecret"] = self.api_secret
        if self.passphrase:
            creds["passphrase"] = self.passphrase
        return creds if creds else None


class Kalshi(Exchange):
    """Kalshi exchange client."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        private_key: Optional[str] = None,
        base_url: Optional[str] = None,
        auto_start_server: Optional[bool] = None,
        pmxt_api_key: Optional[str] = None,
    ):
        """
        Initialize Kalshi client.

        Args:
            api_key: API key for authentication (optional)
            private_key: Private key for authentication (optional)
            base_url: Base URL of the PMXT sidecar server
            auto_start_server: Automatically start server if not running (default: True)
            pmxt_api_key: Hosted PMXT API key (optional; enables hosted mode)
        """
        super().__init__(
            exchange_name="kalshi",
            api_key=api_key,
            private_key=private_key,
            base_url=base_url,
            auto_start_server=auto_start_server,
            pmxt_api_key=pmxt_api_key,
        )


class KalshiDemo(Exchange):
    """KalshiDemo exchange client."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        private_key: Optional[str] = None,
        base_url: Optional[str] = None,
        auto_start_server: Optional[bool] = None,
        pmxt_api_key: Optional[str] = None,
    ):
        """
        Initialize KalshiDemo client.

        Args:
            api_key: API key for authentication (optional)
            private_key: Private key for authentication (optional)
            base_url: Base URL of the PMXT sidecar server
            auto_start_server: Automatically start server if not running (default: True)
            pmxt_api_key: Hosted PMXT API key (optional; enables hosted mode)
        """
        super().__init__(
            exchange_name="kalshi-demo",
            api_key=api_key,
            private_key=private_key,
            base_url=base_url,
            auto_start_server=auto_start_server,
            pmxt_api_key=pmxt_api_key,
        )


class Probable(Exchange):
    """Probable exchange client."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        api_secret: Optional[str] = None,
        passphrase: Optional[str] = None,
        private_key: Optional[str] = None,
        base_url: Optional[str] = None,
        auto_start_server: Optional[bool] = None,
        pmxt_api_key: Optional[str] = None,
    ):
        """
        Initialize Probable client.

        Args:
            api_key: API key for authentication (optional)
            api_secret: API secret for authentication (optional)
            passphrase: Passphrase for authentication (optional)
            private_key: Private key for authentication (optional)
            base_url: Base URL of the PMXT sidecar server
            auto_start_server: Automatically start server if not running (default: True)
            pmxt_api_key: Hosted PMXT API key (optional; enables hosted mode)
        """
        super().__init__(
            exchange_name="probable",
            api_key=api_key,
            private_key=private_key,
            base_url=base_url,
            auto_start_server=auto_start_server,
            pmxt_api_key=pmxt_api_key,
        )

        self.api_secret = api_secret
        self.passphrase = passphrase

    def _get_credentials_dict(self) -> Optional[Dict[str, Any]]:
        creds = super()._get_credentials_dict() or {}
        if self.api_secret:
            creds["apiSecret"] = self.api_secret
        if self.passphrase:
            creds["passphrase"] = self.passphrase
        return creds if creds else None


class Baozi(Exchange):
    """Baozi exchange client."""

    def __init__(
        self,
        private_key: Optional[str] = None,
        base_url: Optional[str] = None,
        auto_start_server: Optional[bool] = None,
        pmxt_api_key: Optional[str] = None,
    ):
        """
        Initialize Baozi client.

        Args:
            private_key: Private key for authentication (optional)
            base_url: Base URL of the PMXT sidecar server
            auto_start_server: Automatically start server if not running (default: True)
            pmxt_api_key: Hosted PMXT API key (optional; enables hosted mode)
        """
        super().__init__(
            exchange_name="baozi",
            private_key=private_key,
            base_url=base_url,
            auto_start_server=auto_start_server,
            pmxt_api_key=pmxt_api_key,
        )


class Myriad(Exchange):
    """Myriad exchange client."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        wallet_address: Optional[str] = None,
        base_url: Optional[str] = None,
        auto_start_server: Optional[bool] = None,
        pmxt_api_key: Optional[str] = None,
    ):
        """
        Initialize Myriad client.

        Args:
            api_key: API key for authentication (optional)
            wallet_address: Wallet address (required for positions and balance)
            base_url: Base URL of the PMXT sidecar server
            auto_start_server: Automatically start server if not running (default: True)
            pmxt_api_key: Hosted PMXT API key (optional; enables hosted mode)
        """
        super().__init__(
            exchange_name="myriad",
            api_key=api_key,
            private_key=wallet_address,
            base_url=base_url,
            auto_start_server=auto_start_server,
            pmxt_api_key=pmxt_api_key,
        )


class Opinion(Exchange):
    """Opinion exchange client."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        private_key: Optional[str] = None,
        proxy_address: Optional[str] = None,
        base_url: Optional[str] = None,
        auto_start_server: Optional[bool] = None,
        pmxt_api_key: Optional[str] = None,
    ):
        """
        Initialize Opinion client.

        Args:
            api_key: API key for authentication (optional)
            private_key: Private key for authentication (optional)
            proxy_address: Proxy/smart wallet address (optional)
            base_url: Base URL of the PMXT sidecar server
            auto_start_server: Automatically start server if not running (default: True)
            pmxt_api_key: Hosted PMXT API key (optional; enables hosted mode)
        """
        super().__init__(
            exchange_name="opinion",
            api_key=api_key,
            private_key=private_key,
            proxy_address=proxy_address,
            base_url=base_url,
            auto_start_server=auto_start_server,
            pmxt_api_key=pmxt_api_key,
        )


class Metaculus(Exchange):
    """Metaculus exchange client."""

    def __init__(
        self,
        api_token: Optional[str] = None,
        base_url: Optional[str] = None,
        auto_start_server: Optional[bool] = None,
        pmxt_api_key: Optional[str] = None,
    ):
        """
        Initialize Metaculus client.

        Args:
            api_token: API token for authentication (optional; required for Metaculus API access)
            base_url: Base URL of the PMXT sidecar server
            auto_start_server: Automatically start server if not running (default: True)
            pmxt_api_key: Hosted PMXT API key (optional; enables hosted mode)
        """
        super().__init__(
            exchange_name="metaculus",
            api_token=api_token,
            base_url=base_url,
            auto_start_server=auto_start_server,
            pmxt_api_key=pmxt_api_key,
        )


class Smarkets(Exchange):
    """Smarkets exchange client."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        private_key: Optional[str] = None,
        base_url: Optional[str] = None,
        auto_start_server: Optional[bool] = None,
        pmxt_api_key: Optional[str] = None,
    ):
        """
        Initialize Smarkets client.

        Args:
            api_key: API key for authentication (optional)
            private_key: Private key for authentication (optional)
            base_url: Base URL of the PMXT sidecar server
            auto_start_server: Automatically start server if not running (default: True)
            pmxt_api_key: Hosted PMXT API key (optional; enables hosted mode)
        """
        super().__init__(
            exchange_name="smarkets",
            api_key=api_key,
            private_key=private_key,
            base_url=base_url,
            auto_start_server=auto_start_server,
            pmxt_api_key=pmxt_api_key,
        )


class PolymarketUS(Exchange):
    """PolymarketUS exchange client."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        private_key: Optional[str] = None,
        base_url: Optional[str] = None,
        auto_start_server: Optional[bool] = None,
        pmxt_api_key: Optional[str] = None,
    ):
        """
        Initialize PolymarketUS client.

        Args:
            api_key: API key for authentication (optional)
            private_key: Private key for authentication (optional)
            base_url: Base URL of the PMXT sidecar server
            auto_start_server: Automatically start server if not running (default: True)
            pmxt_api_key: Hosted PMXT API key (optional; enables hosted mode)
        """
        super().__init__(
            exchange_name="polymarket_us",
            api_key=api_key,
            private_key=private_key,
            base_url=base_url,
            auto_start_server=auto_start_server,
            pmxt_api_key=pmxt_api_key,
        )


class Hyperliquid(Exchange):
    """Hyperliquid exchange client."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        private_key: Optional[str] = None,
        base_url: Optional[str] = None,
        auto_start_server: Optional[bool] = None,
        pmxt_api_key: Optional[str] = None,
    ):
        """
        Initialize Hyperliquid client.

        Args:
            api_key: API key for authentication (optional)
            private_key: Private key for authentication (optional)
            base_url: Base URL of the PMXT sidecar server
            auto_start_server: Automatically start server if not running (default: True)
            pmxt_api_key: Hosted PMXT API key (optional; enables hosted mode)
        """
        super().__init__(
            exchange_name="hyperliquid",
            api_key=api_key,
            private_key=private_key,
            base_url=base_url,
            auto_start_server=auto_start_server,
            pmxt_api_key=pmxt_api_key,
        )


class GeminiTitan(Exchange):
    """GeminiTitan exchange client."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        api_secret: Optional[str] = None,
        base_url: Optional[str] = None,
        auto_start_server: Optional[bool] = None,
        pmxt_api_key: Optional[str] = None,
    ):
        """
        Initialize GeminiTitan client.

        Args:
            api_key: API key for authentication (optional)
            api_secret: API secret for authentication (optional)
            base_url: Base URL of the PMXT sidecar server
            auto_start_server: Automatically start server if not running (default: True)
            pmxt_api_key: Hosted PMXT API key (optional; enables hosted mode)
        """
        super().__init__(
            exchange_name="gemini-titan",
            api_key=api_key,
            base_url=base_url,
            auto_start_server=auto_start_server,
            pmxt_api_key=pmxt_api_key,
        )

        self.api_secret = api_secret

    def _get_credentials_dict(self) -> Optional[Dict[str, Any]]:
        creds = super()._get_credentials_dict() or {}
        if self.api_secret:
            creds["apiSecret"] = self.api_secret
        return creds if creds else None


class Mock(Exchange):
    """Mock exchange client."""

    def __init__(
        self,
        base_url: Optional[str] = None,
        auto_start_server: Optional[bool] = None,
        pmxt_api_key: Optional[str] = None,
    ):
        """
        Initialize Mock client.

        Args:
            base_url: Base URL of the PMXT sidecar server
            auto_start_server: Automatically start server if not running (default: True)
            pmxt_api_key: Hosted PMXT API key (optional; enables hosted mode)
        """
        super().__init__(
            exchange_name="mock",
            base_url=base_url,
            auto_start_server=auto_start_server,
            pmxt_api_key=pmxt_api_key,
        )


class Router(Exchange):
    """Router exchange client."""

    def __init__(
        self,
        base_url: Optional[str] = None,
        auto_start_server: Optional[bool] = None,
        pmxt_api_key: Optional[str] = None,
    ):
        """
        Initialize Router client.

        Args:
            base_url: Base URL of the PMXT sidecar server
            auto_start_server: Automatically start server if not running (default: True)
            pmxt_api_key: Hosted PMXT API key (optional; enables hosted mode)
        """
        super().__init__(
            exchange_name="router",
            base_url=base_url,
            auto_start_server=auto_start_server,
            pmxt_api_key=pmxt_api_key,
        )

# Backwards-compatible aliases for exchange classes generated before underscore handling.
Polymarket_us = PolymarketUS
